default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: sqroot

production:
  adapter: postgresql
  host: ec2-54-221-210-126.compute-1.amazonaws.com
  database: dci6bdva7d3q2g
  user: orlndldppzsbsg
  port: 5432
  password: 16c9b40a5a9e74fd6c0eb3070d1753bbaeb051937fe608de891d44d34adc8a09
  uri: postgres://orlndldppzsbsg:16c9b40a5a9e74fd6c0eb3070d1753bbaeb051937fe608de891d44d34adc8a09@ec2-54-221-210-126.compute-1.amazonaws.com:5432/dci6bdva7d3q2g